#!/bin/bash

MODE=

for arg; do
  case $arg in
    --qr)
      shift
      MODE=qr
      ;;

    --shell)
      shift
      MODE=shell
      ;;

    --write)
      shift
      MODE=write
      ;;

    --up)
      shift
      MODE=up
      ;;

    --down)
      shift
      MODE=down
      ;;

    --default)
      shift
      export DEFAULT_GW=yes
      ;;

    --*)
      echo "unknown $arg."
      exit 1
      ;;
    
    *)
      break
      ;;
  esac
done

server_name="$1"
server_config="servers/$server_name.conf"

client_name="$2"
client_config="clients/$client_name.conf"

qr_emit() {
  $@ | qrencode -t ansiutf8
}

shell_emit() {
  echo "cat <<EOF > /etc/wireguard/wg-${server_name}.conf"
  $@
  echo "EOF"
  echo ""
  echo "systemctl enable wg-quick@wg-${server_name}.service"
  echo "systemctl restart wg-quick@wg-${server_name}.service"
}

write_emit() {
  set -x
  umask 0077
  $@ > "wg-${server_name}.conf"
}

wg_quick_emit() {
  wg_name="$(pwd)/wg-${server_name}.conf"

  ACTION="$1"
  shift

  set -x
  umask 0077
  $@ > "wg-${server_name}.conf"
  wg-quick "$ACTION" "$wg_name"
}

up_emit() {
  wg_quick_emit "up" "$@"
}

down_emit() {
  wg_quick_emit "down" "$@"
}

if [[ -n "$MODE" ]]; then
  ${MODE}_emit "$0" "$@"
  exit 0
fi

usage() {
  APP="$1"
  shift
  stderr "$APP" "[options]" "$@"
  stderr ""
  stderr "Options:"
  stderr " --qr: output QR code"
  stderr " --shell: output shell commands"
  stderr " --write: write configuration file"
  stderr " --up: wg-quick up"
  stderr " --down: wg-quick down"
  stderr ""
  exit 1
}
