#!/usr/bin/env bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "$DIR/helpers/functions"

if [[ $# -ne 5 ]]; then
  echo "usage: $0 <name> <endpoint> <address-with-subnet> <start-ip> <end-ip>"
  exit 1
fi

validate_name "$1"

if [[ -e "servers/$1.conf" ]]; then
  echo "The servers/$1.conf already exist!"
  exit 1
fi

PrivateKey="$(wg genkey)"
PublicKey="$(echo "$PrivateKey" | wg pubkey)"
PresharedKey="$(wg genpsk)"
Endpoint="$2"
Address="$3"
StartIp="$4"
EndIp="$5"

cat <<EOF > servers/$1.conf
PrivateKey="$PrivateKey"
PublicKey="$PublicKey"
PresharedKey="$PresharedKey"
Endpoint="$Endpoint"
Address="$Address"
StartIp="$StartIp"
EndIp="$EndIp"
ListenPort="$DEFAULT_LISTEN_PORT"
DNS="1.1.1.1"
DefaultGateway=""
EOF
