#!/bin/bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "$DIR/helpers/functions"
source "$DIR/helpers/cmd-emit"

run_server_and_client "$@"

load_config "$server_config"
emit_config_interface "$client_config" "$server_config"
emit_config_peer "$server_config" "$client_config"
