#!/bin/bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "$DIR/helpers/functions"
source "$DIR/helpers/cmd-emit"

if [[ $# -ne 2 ]]; then
  usage "$0" "<server>" "<client>"
fi

if [[ ! -e "$client_config" ]]; then
  echo "The $client_config does not exist!"
  exit 1
fi

if [[ ! -e "$server_config" ]]; then
  echo "The $server_config does not exist!"
  exit 1
fi

load_config "$server_config"
emit_config_interface "$client_config" "$server_config"
emit_config_peer "$server_config" "$client_config"
