#!/bin/bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "$DIR/helpers/functions"

rm -rf configs/*

umask 0077

for server_config in "servers/"*.conf; do
  server_name="$(basename "$server_config" .conf)"

  echo "$server_name..."

  "$DIR/emit-server" --write "$server_name"

  for client_config in "clients/"*.conf; do
    echo "$server_name:$client_name..."

    client_name="$(basename "$client_config" .conf)"

    "$DIR/emit-client" --write "$server_name" "$client_name"
    "$DIR/emit-client" --write --default "$server_name" "$client_name"
  done
done

echo Done.
