#!/bin/bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "$DIR/helpers/functions"

match() {
  key="$1"
  shift
  if [[ $# -eq 0 ]]; then
    return 0
  fi

  for match; do
    if [[ "$key" == $match ]]; then
      return 0
    fi
  done

  return 1
}

echo "Servers:"
for server_config in "servers/"*.conf; do
  server_name="$(basename "$server_config" .conf)"

  if ! match "$server_name" "$@"; then
    continue
  fi

  server_updatecmd=$(get_value "$server_config" "UpdateCmd")

  if [[ -n "$server_updatecmd" ]]; then
    echo "$server_name... "
    "$DIR/emit-server" $server_updatecmd "$server_name"
  fi
done

echo
echo "Clients:"

for client_config in "clients/"*.conf; do
  client_name="$(basename "$client_config" .conf)"

  if ! match "$client_name" "$@"; then
    continue
  fi

  for server_config in "servers/"*.conf; do
    server_name="$(basename "$server_config" .conf)"
    client_updatecmd=$(get_value "$client_config" "UpdateCmd_$server_name" "UpdateCmd")
    client_disallowed=$(get_value "$client_config" "Interface_$server_name")

    if ! match "$server_name" "$@"; then
      continue
    fi

    if [[ "$client_disallowed" == 0 ]]; then
      continue
    fi

    if [[ -n "$client_updatecmd" ]]; then
      echo "$client_name:$server_name... "
      "$DIR/emit-client" $client_updatecmd "$server_name" "$client_name"
    fi
  done
done

echo Done.
